### ISSUE TITLE
Test clean_db()

### ISSUE THREAD

**Issue by joshmiller17** [joshmiller17/foldit-view-data#4]
Add debugging log of how many entries were removed from each step of the cleaning process.

**Comment by joshmiller17** [comment]
Need to successfully run clean_db in a reasonable amount of time. When I tried running it (after fixing some typos), removing Beginner puzzles from the options database went on for several hours before I interrupted the program. Code should either work within minutes or print progress and status updates on occasion.

**Comment by lee-vivian** [comment]
I added status updates for the first 3 steps in the clean_db process (removing error entries, removing invalid puzzle ranks, removing beginner puzzle entries) and refactored the code for removing beginner puzzle entries. It looks like each step within remove_beginnner_puzzle_entries works within a few minutes now except for the last step to remove beginner entries from the options table. I left that running for a few hours overnight. I created a new pull request to show the current changes (not ready to be merged yet) and will continue looking into fixing this issue this afternoon.

**Comment by lee-vivian** [comment]
![console output](https://user-images.githubusercontent.com/23562271/54490232-6f35e300-488a-11e9-885d-d74df5c72d86.png)

**Comment by lee-vivian** [comment]
It seems like the issue with remove_beginner_puzzle_entries taking an exorbitant amount of time is due to the step where entries are removed from the options table (i'm guessing because the table is so large)

In remove_beginner_entries, 88,349 entries are removed from the ranks table in ~1 min but even though only 77,927 entries are identified to be removed from the options table, it can take many hours. Similarly, for remove_intro_puzzle_entries, removing 84,008 entries from the options table will take a very long time.

I updated my pull request with a new idea to handle this issue. Removing/cleaning entries from the puzzle and ranks tables seems to work fine, but instead of removing entries from the options table for beginner and intro puzzles, I created a global dictionary var BEGINNER_INTRO_OPTION_PIDS that contains a key for each PID in the options table and a value for whether it is a beginner or intro puzzle (true) or not (false). Running the script up until remove_intro_puzzle_entries takes a much shorter amount of time then and I was thinking that when we need to query the options table in later functions, we can just add a check ("if BEGINNER_INTRO_OPTION_PIDS[pid]") to determine if we should consider that entry.

**Comment by lee-vivian** [comment]
![console output](https://user-images.githubusercontent.com/23562271/54555945-341cd800-498e-11e9-8a64-69f9b76a8174.png)

**Comment by lee-vivian** [comment]
Also if we need to determine how many entries are excluded from the options table because they are Beginner/Intro puzzles, we could then just do something like sum(BEGINNER_INTRO_OPTION_PIDS.values)

**Comment by joshmiller17** [comment]
@lee-vivian can you benchmark how long it takes to remove 1, 10, and 100 entries? The problem might just be that you're trying to remove them all at once, and if you iterate through them in batches, it has to load less in memory all at once. Not sure, but worth testing. If nothing else, this tells us approximately how long it should take to remove all 90,000 entries. If it's a reasonable amount of time, we can just run it and save the DB. We only need to run that code once and save a copy of the cleaned DB.

**Comment by joshmiller17** [comment]
If we do have to use something like your BEGINNER_INTRO_OPTION_PIDS dict, I would prefer to make a streamlined filter_and_query function that all of our queries use, which takes an input the query string and outputs the query after filters were applied (somehow merge the query with our filters).

**Comment by lee-vivian** [comment]
With the current implementation of removing one entry at a time:
- avg time to remove 1 entry:  0.6215 seconds
- avg time to remove 10 entries 5.7679 seconds
- avg time to remove 100 entries 58.6281 seconds

**Comment by lee-vivian** [comment]
![100 entries per time](https://user-images.githubusercontent.com/23562271/54562281-14d97700-499d-11e9-9387-2e33efdc0ad8.png)
![10 entries per time](https://user-images.githubusercontent.com/23562271/54562284-15720d80-499d-11e9-94c4-d8d3f5ac1d65.png)
![1 entry per time](https://user-images.githubusercontent.com/23562271/54562285-15720d80-499d-11e9-949f-2945ead9d772.png)

**Comment by lee-vivian** [comment]
missing_dict info for remove_major_missing_entries (data inputted into excel file for readability) 
![missing dict for remove_major_missing_entries](https://user-images.githubusercontent.com/23562271/54644095-e2984a00-4a6e-11e9-8ff2-b9e5dcd7270d.png)
